import type { SequenceDefinition } from '../schema'

export const cineSequence: SequenceDefinition = {
  id: "cine",
  name: "Cine",
  sections: [
    {
      id: "cine-availability",
      name: "Available Series & Artefacts",
      fields: [
        {
          id: "series_availability",
          name: "Available Series",
          type: "series_availability",
          required: true,
          options: ["SAX", "2CH", "3CH", "4CH"],
        },
        {
          id: "artefacts_grade",
          name: "Artefacts Grade",
          type: "categorical",
          required: true,
          options: ["0", "1", "2", "3", "4"],
        },
        {
          id: "artefacts_type",
          name: "Artefacts Type",
          type: "categorical",
          required: false,
          options: ["Ghosting (motion)", "Wrapping", "Flow", "Metal", "Arrhythmia"],
        },
      ],
    },
    {
      id: "cine-lv",
      name: "Left Ventricle",
      fields: [
        {
          id: "wall_motion_abnormalities",
          name: "Wall Motion Abnormalities",
          type: "boolean",
          required: true,
        },
        {
          id: "wall_motion_segments",
          name: "Wall Motion Segments",
          type: "segment_categorical",
          required: true,
          segmentCount: 17,
          options: ["Normal", "Hypokinetic", "Akinetic", "Dyskinetic"],
          defaultValue: Object.fromEntries(Array.from({ length: 17 }, (_, i) => [i + 1, "Normal"])),
        },
        {
          id: "wall_motion_global",
          name: "Global Wall Motion",
          type: "boolean",
          required: true,
        },
        { id: "asynchronism", name: "Asynchronism", type: "boolean", required: true },
        { id: "lv_measurable", name: "LV Measurable", type: "boolean", required: true, defaultValue: true },
        {
          id: "visual_lvef",
          name: "Visual LVEF",
          type: "numeric",
          required: true,
          unit: "%",
          min: 10,
          max: 80,
          calibrationTolerance: { absolute: 5, relativePercent: 8 },
        },
        {
          id: "lvef",
          name: "LVEF",
          type: "numeric",
          required: true,
          unit: "%",
          min: 10,
          max: 80,
          conditionalOn: { fieldId: "lv_measurable", value: true },
          calibrationTolerance: { absolute: 5, relativePercent: 8 },
        },
        {
          id: "lv_edv",
          name: "LV EDV",
          type: "numeric",
          required: true,
          unit: "mL",
          min: 30,
          max: 350,
          conditionalOn: { fieldId: "lv_measurable", value: true },
          calibrationTolerance: { absolute: 15, relativePercent: 10 },
        },
        {
          id: "lv_esv",
          name: "LV ESV",
          type: "numeric",
          required: true,
          unit: "mL",
          min: 20,
          max: 300,
          conditionalOn: { fieldId: "lv_measurable", value: true },
          calibrationTolerance: { absolute: 15, relativePercent: 10 },
        },
        {
          id: "lv_mass",
          name: "LV Mass",
          type: "numeric",
          required: true,
          unit: "g",
          min: 50,
          max: 300,
          conditionalOn: { fieldId: "lv_measurable", value: true },
          calibrationTolerance: { absolute: 10, relativePercent: 8 },
        },
        {
          id: "ed_max_thickness",
          name: "ED Max Wall Thickness",
          type: "numeric",
          required: false,
          unit: "mm",
          min: 1,
          max: 40,
          conditionalOn: { fieldId: "lv_measurable", value: true },
          calibrationTolerance: { absolute: 2, relativePercent: 15 },
        },
      ],
    },
    {
      id: "cine-rv",
      name: "Right Ventricle",
      fields: [
        { id: "rv_wall_motion", name: "RV Wall Motion Abnormalities", type: "boolean", required: true },
        { id: "rv_visual_dysfunction", name: "RV Visual Dysfunction", type: "boolean", required: true },
        {
          id: "tapse",
          name: "TAPSE",
          type: "numeric",
          required: false,
          unit: "mm",
          min: 1,
          max: 50,
          calibrationTolerance: { absolute: 3, relativePercent: 15 },
        },
        { id: "rv_measurable", name: "RV Measurable", type: "boolean", required: true, defaultValue: true },
        {
          id: "rvef",
          name: "RVEF",
          type: "numeric",
          required: true,
          unit: "%",
          min: 10,
          max: 80,
          conditionalOn: { fieldId: "rv_measurable", value: true },
          calibrationTolerance: { absolute: 5, relativePercent: 8 },
        },
        {
          id: "rv_edv",
          name: "RV EDV",
          type: "numeric",
          required: true,
          unit: "mL",
          min: 0,
          max: 500,
          conditionalOn: { fieldId: "rv_measurable", value: true },
          calibrationTolerance: { absolute: 15, relativePercent: 10 },
        },
        {
          id: "rv_esv",
          name: "RV ESV",
          type: "numeric",
          required: true,
          unit: "mL",
          min: 0,
          max: 400,
          conditionalOn: { fieldId: "rv_measurable", value: true },
          calibrationTolerance: { absolute: 15, relativePercent: 10 },
        },
      ],
    },
    {
      id: "cine-atria",
      name: "Atria",
      fields: [
        { id: "la_measurable", name: "LA Measurable", type: "boolean", required: true, defaultValue: true },
        {
          id: "la_biplanar_smallest",
          name: "LA Smallest Vol.",
          type: "numeric",
          required: true,
          unit: "mL",
          min: 5,
          max: 60,
          conditionalOn: { fieldId: "la_measurable", value: true },
          calibrationTolerance: { absolute: 5, relativePercent: 15 },
        },
        {
          id: "la_biplanar_largest",
          name: "LA Largest Vol.",
          type: "numeric",
          required: true,
          unit: "mL",
          min: 5,
          max: 50,
          conditionalOn: { fieldId: "la_measurable", value: true },
          calibrationTolerance: { absolute: 5, relativePercent: 15 },
        },
        { id: "ra_measurable", name: "RA Measurable", type: "boolean", required: true, defaultValue: true },
        {
          id: "ra_4c_smallest",
          name: "RA Smallest Area",
          type: "numeric",
          required: true,
          unit: "cm2",
          min: 5,
          max: 60,
          conditionalOn: { fieldId: "ra_measurable", value: true },
          calibrationTolerance: { absolute: 5, relativePercent: 15 },
        },
        {
          id: "ra_4c_largest",
          name: "RA Largest Area",
          type: "numeric",
          required: true,
          unit: "cm2",
          min: 5,
          max: 50,
          conditionalOn: { fieldId: "ra_measurable", value: true },
          calibrationTolerance: { absolute: 5, relativePercent: 15 },
        },
      ],
    },
    {
      id: "cine-pericardium",
      name: "Pericardium",
      fields: [
        {
          id: "pericardial_effusion",
          name: "Pericardial Effusion Thickness",
          type: "categorical",
          required: true,
          options: ["0", "1", "2", "3"],
        },
      ],
    },
  ],
}
