import type { SequenceDefinition } from '../schema'

export const lgeSequence: SequenceDefinition = {
  id: "lge",
  name: "LGE",
  sections: [
    {
      id: "lge-availability",
      name: "Availability & Artefacts",
      fields: [
        { id: "lge_available", name: "LGE Available", type: "boolean", required: true },
        {
          id: "sequence_used",
          name: "Sequence Used",
          type: "categorical",
          required: true,
          options: ["FLASH", "PSIR-PSIR", "PSIR-MAG"],
          conditionalOn: { fieldId: "lge_available", value: true },
        },
        {
          id: "artefacts_grade",
          name: "Artefacts Grade",
          type: "categorical",
          required: true,
          options: ["0", "1", "2", "3", "4"],
          conditionalOn: { fieldId: "lge_available", value: true },
        },
        {
          id: "artefacts_type",
          name: "Artefacts Type",
          type: "categorical",
          required: false,
          options: ["Ghosting (motion)", "Wrapping", "Flow", "Metal", "Arrhythmia", "Imperfect Ti selection"],
          conditionalOn: { fieldId: "lge_available", value: true },
        },
        {
          id: "segments_analysable",
          name: "All Segments Analysable",
          type: "boolean",
          required: true,
          conditionalOn: { fieldId: "lge_available", value: true },
        },
      ],
    },
    {
      id: "lge-lv",
      name: "LV LGE",
      fields: [
        {
          id: "lge_presence",
          name: "LGE Presence",
          type: "boolean",
          required: true,
          conditionalOn: { fieldId: "lge_available", value: true },
        },
        {
          id: "lge_segments",
          name: "LGE Segments",
          type: "segment_categorical",
          required: true,
          segmentCount: 17,
          options: ["Sub-epicardial", "Intra-myocardial", "Sub-endocardial", "Transmural (epi)", "Transmural (endo)", "Mixed", "None"],
          defaultValue: Object.fromEntries(Array.from({ length: 17 }, (_, i) => [i + 1, "None"])),
          conditionalOn: { fieldId: "lge_presence", value: true },
        },
        {
          id: "visual_quantification",
          name: "Visual Quantification",
          type: "numeric",
          required: true,
          min: 0,
          max: 17,
          conditionalOn: { fieldId: "lge_presence", value: true },
          calibrationTolerance: { absolute: 1, relativePercent: 20 },
        },
        {
          id: "lge_mass",
          name: "LGE Mass",
          type: "numeric",
          required: false,
          unit: "g",
          min: 0,
          max: 300,
          conditionalOn: { fieldId: "lge_presence", value: true },
          calibrationTolerance: { absolute: 3, relativePercent: 15 },
        },
        {
          id: "lge_percentage",
          name: "LGE Percentage",
          type: "numeric",
          required: false,
          unit: "%",
          min: 0,
          max: 100,
          conditionalOn: { fieldId: "lge_presence", value: true },
          calibrationTolerance: { absolute: 3, relativePercent: 15 },
        },
      ],
    },
    {
      id: "lge-pericardial",
      name: "Pericardial LGE",
      fields: [
        {
          id: "pericardial_lge",
          name: "Pericardial LGE",
          type: "categorical",
          required: true,
          options: ["N", "L", "D"],
          conditionalOn: { fieldId: "lge_available", value: true },
        },
      ],
    },
  ],
}
