import type { SequenceDefinition } from '../schema'

export const t1MappingPreSequence: SequenceDefinition = {
  id: "t1-mapping-pre",
  name: "T1 Mapping Pre",
  sections: [
    {
      id: "t1-pre-availability",
      name: "Availability & Artefacts",
      fields: [
        { id: "t1_pre_available", name: "T1 Pre Available", type: "boolean", required: true },
        {
          id: "basal_available",
          name: "Basal Slice Available",
          type: "boolean",
          required: true,
          conditionalOn: { fieldId: "t1_pre_available", value: true },
        },
        {
          id: "medial_available",
          name: "Medial Slice Available",
          type: "boolean",
          required: true,
          conditionalOn: { fieldId: "t1_pre_available", value: true },
        },
        {
          id: "apical_available",
          name: "Apical Slice Available",
          type: "boolean",
          required: true,
          conditionalOn: { fieldId: "t1_pre_available", value: true },
        },
        {
          id: "artefacts_grade",
          name: "Artefacts Grade",
          type: "categorical",
          required: true,
          options: ["0", "1", "2", "3", "4"],
          conditionalOn: { fieldId: "t1_pre_available", value: true },
        },
        {
          id: "artefacts_type",
          name: "Artefacts Type",
          type: "categorical",
          required: false,
          options: ["Bad MOCO", "Wrapping", "Other"],
          conditionalOn: { fieldId: "t1_pre_available", value: true },
        },
      ],
    },
    {
      id: "t1-pre-values",
      name: "T1 Values",
      fields: [
        {
          id: "mid_ivs",
          name: "Mid IVS T1",
          type: "numeric",
          required: true,
          unit: "ms",
          min: 500,
          max: 2000,
          conditionalOn: { fieldId: "t1_pre_available", value: true },
          calibrationTolerance: { absolute: 30, relativePercent: 3 },
        },
        {
          id: "presence_local_elevation",
          name: "Presence of Local Elevation",
          type: "boolean",
          required: true,
          conditionalOn: { fieldId: "t1_pre_available", value: true },
        },
        {
          id: "local_elevation",
          name: "Local Elevation Value",
          type: "numeric",
          required: true,
          unit: "ms",
          min: 500,
          max: 2000,
          conditionalOn: { fieldId: "presence_local_elevation", value: true },
          calibrationTolerance: { absolute: 30, relativePercent: 3 },
        },
        {
          id: "t1_segments",
          name: "T1 Segment Values",
          type: "segment_numeric",
          required: false,
          segmentCount: 16,
          unit: "ms",
          min: 0,
          max: 2500,
          conditionalOn: { fieldId: "t1_pre_available", value: true },
        },
      ],
    },
  ],
}
